// <auto-generated />
using System;
using BlendIt.Test.Repository.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlendIt.Test.Repository.Migrations
{
    [DbContext(typeof(EntityContext))]
    [Migration("20200206055657_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlendIt.Test.Domain.Teachers.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnName("registration")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Removed")
                        .HasColumnName("removed")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("idTeacher");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("BlendIt.Test.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("password")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Removed")
                        .HasColumnName("removed")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
